# Generated by Django 4.2 on 2023-06-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="highlighted",
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="owner",
        ),
    ]
